version: '3'

services:
# nom du servcers ou services à paramétrer
  config-server:
  # bloc de contruction (Build) avec ts les param de servre/services un/un
    build:
  # context = là où ça se passe = chemin vers l'élément(ciblé)
      context: /home/vagrant/projetgestionvetclinic/spring-petclinic-config-server
  # nom du dockerfile qui sera utilisé
      dockerfile: Dockerfile
  # nom du container qui va être créé
    container_name: config-server
  # ci-dessous le paramétrage deploiement (repré&senté par ce bloc deploy:)
    deploy:
  # définition des ressources avec des valures max, min
      resources:
        limits:
          memory: 512M
  # No du ports qui sera utilisé
    ports:
     - 8888:8888

  discovery-server:
    build:
      context: /home/vagrant/projetgestionvetclinic/spring-petclinic-discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - config-server
    ports:
     - 8761:8761

  customers-service:
    build:
      context: /home/vagrant/projetgestionvetclinic/spring-petclinic-customers-service
      dockerfile: Dockerfile
    container_name: customers-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - config-server
      - discovery-server
    ports:
    - 8081:8081

  visits-service:
    build:
      context: /home/vagrant/projetgestionvetclinic/spring-petclinic-visits-service
      dockerfile: Dockerfile
    container_name: visits-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - config-server
      - discovery-server
    ports:
     - 8082:8082

  vets-service:
    build:
      context: /home/vagrant/projetgestionvetclinic/spring-petclinic-vets-service
      dockerfile: Dockerfile
    container_name: vets-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - config-server
      - discovery-server
    ports:
     - 8083:8083

  api-gateway:
    build:
      context: /home/vagrant/projetgestionvetclinic/spring-petclinic-api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
     - config-server
     - discovery-server
     - customers-service
     - vets-service
     - visits-service
    ports:
     - 8080:8080




